// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
	_ "wps_store/rpc/google/api"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutObjectRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Publicread           string   `protobuf:"bytes,4,opt,name=publicread,proto3" json:"publicread,omitempty"`
	Contenttype          string   `protobuf:"bytes,5,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	Contentmaxlength     int64    `protobuf:"varint,6,opt,name=contentmaxlength,proto3" json:"contentmaxlength,omitempty"`
	Filecontent          string   `protobuf:"bytes,7,opt,name=filecontent,proto3" json:"filecontent,omitempty"`
	Expiretime           int64    `protobuf:"varint,8,opt,name=expiretime,proto3" json:"expiretime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectRequest) Reset()         { *m = PutObjectRequest{} }
func (m *PutObjectRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest) ProtoMessage()    {}
func (*PutObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *PutObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest.Unmarshal(m, b)
}
func (m *PutObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest.Marshal(b, m, deterministic)
}
func (m *PutObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest.Merge(m, src)
}
func (m *PutObjectRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest.Size(m)
}
func (m *PutObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest proto.InternalMessageInfo

func (m *PutObjectRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *PutObjectRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *PutObjectRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutObjectRequest) GetPublicread() string {
	if m != nil {
		return m.Publicread
	}
	return ""
}

func (m *PutObjectRequest) GetContenttype() string {
	if m != nil {
		return m.Contenttype
	}
	return ""
}

func (m *PutObjectRequest) GetContentmaxlength() int64 {
	if m != nil {
		return m.Contentmaxlength
	}
	return 0
}

func (m *PutObjectRequest) GetFilecontent() string {
	if m != nil {
		return m.Filecontent
	}
	return ""
}

func (m *PutObjectRequest) GetExpiretime() int64 {
	if m != nil {
		return m.Expiretime
	}
	return 0
}

type PutObjectResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectResponse) Reset()         { *m = PutObjectResponse{} }
func (m *PutObjectResponse) String() string { return proto.CompactTextString(m) }
func (*PutObjectResponse) ProtoMessage()    {}
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *PutObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectResponse.Unmarshal(m, b)
}
func (m *PutObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectResponse.Marshal(b, m, deterministic)
}
func (m *PutObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectResponse.Merge(m, src)
}
func (m *PutObjectResponse) XXX_Size() int {
	return xxx_messageInfo_PutObjectResponse.Size(m)
}
func (m *PutObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectResponse proto.InternalMessageInfo

func (m *PutObjectResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutObjectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PutObjectResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetObjectRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Contenttype          string   `protobuf:"bytes,4,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *GetObjectRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *GetObjectRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetObjectRequest) GetContenttype() string {
	if m != nil {
		return m.Contenttype
	}
	return ""
}

type GetObjectResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetObjectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetObjectResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetObjectPresignedUrlRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Expiretime           int64    `protobuf:"varint,4,opt,name=expiretime,proto3" json:"expiretime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectPresignedUrlRequest) Reset()         { *m = GetObjectPresignedUrlRequest{} }
func (m *GetObjectPresignedUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectPresignedUrlRequest) ProtoMessage()    {}
func (*GetObjectPresignedUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *GetObjectPresignedUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectPresignedUrlRequest.Unmarshal(m, b)
}
func (m *GetObjectPresignedUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectPresignedUrlRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectPresignedUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectPresignedUrlRequest.Merge(m, src)
}
func (m *GetObjectPresignedUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectPresignedUrlRequest.Size(m)
}
func (m *GetObjectPresignedUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectPresignedUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectPresignedUrlRequest proto.InternalMessageInfo

func (m *GetObjectPresignedUrlRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *GetObjectPresignedUrlRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *GetObjectPresignedUrlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetObjectPresignedUrlRequest) GetExpiretime() int64 {
	if m != nil {
		return m.Expiretime
	}
	return 0
}

type GetObjectPresignedUrlResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectPresignedUrlResponse) Reset()         { *m = GetObjectPresignedUrlResponse{} }
func (m *GetObjectPresignedUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectPresignedUrlResponse) ProtoMessage()    {}
func (*GetObjectPresignedUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *GetObjectPresignedUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectPresignedUrlResponse.Unmarshal(m, b)
}
func (m *GetObjectPresignedUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectPresignedUrlResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectPresignedUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectPresignedUrlResponse.Merge(m, src)
}
func (m *GetObjectPresignedUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectPresignedUrlResponse.Size(m)
}
func (m *GetObjectPresignedUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectPresignedUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectPresignedUrlResponse proto.InternalMessageInfo

func (m *GetObjectPresignedUrlResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetObjectPresignedUrlResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetObjectPresignedUrlResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PutObjectPresignedUrlRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Publicread           string   `protobuf:"bytes,4,opt,name=publicread,proto3" json:"publicread,omitempty"`
	Contenttype          string   `protobuf:"bytes,5,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	Contentmaxlength     int64    `protobuf:"varint,6,opt,name=contentmaxlength,proto3" json:"contentmaxlength,omitempty"`
	Expiretime           int64    `protobuf:"varint,7,opt,name=expiretime,proto3" json:"expiretime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectPresignedUrlRequest) Reset()         { *m = PutObjectPresignedUrlRequest{} }
func (m *PutObjectPresignedUrlRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectPresignedUrlRequest) ProtoMessage()    {}
func (*PutObjectPresignedUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *PutObjectPresignedUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectPresignedUrlRequest.Unmarshal(m, b)
}
func (m *PutObjectPresignedUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectPresignedUrlRequest.Marshal(b, m, deterministic)
}
func (m *PutObjectPresignedUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectPresignedUrlRequest.Merge(m, src)
}
func (m *PutObjectPresignedUrlRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectPresignedUrlRequest.Size(m)
}
func (m *PutObjectPresignedUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectPresignedUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectPresignedUrlRequest proto.InternalMessageInfo

func (m *PutObjectPresignedUrlRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetPublicread() string {
	if m != nil {
		return m.Publicread
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetContenttype() string {
	if m != nil {
		return m.Contenttype
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetContentmaxlength() int64 {
	if m != nil {
		return m.Contentmaxlength
	}
	return 0
}

func (m *PutObjectPresignedUrlRequest) GetExpiretime() int64 {
	if m != nil {
		return m.Expiretime
	}
	return 0
}

type PutObjectPresignedUrlResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectPresignedUrlResponse) Reset()         { *m = PutObjectPresignedUrlResponse{} }
func (m *PutObjectPresignedUrlResponse) String() string { return proto.CompactTextString(m) }
func (*PutObjectPresignedUrlResponse) ProtoMessage()    {}
func (*PutObjectPresignedUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *PutObjectPresignedUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectPresignedUrlResponse.Unmarshal(m, b)
}
func (m *PutObjectPresignedUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectPresignedUrlResponse.Marshal(b, m, deterministic)
}
func (m *PutObjectPresignedUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectPresignedUrlResponse.Merge(m, src)
}
func (m *PutObjectPresignedUrlResponse) XXX_Size() int {
	return xxx_messageInfo_PutObjectPresignedUrlResponse.Size(m)
}
func (m *PutObjectPresignedUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectPresignedUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectPresignedUrlResponse proto.InternalMessageInfo

func (m *PutObjectPresignedUrlResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutObjectPresignedUrlResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PutObjectPresignedUrlResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*PutObjectRequest)(nil), "proto.PutObjectRequest")
	proto.RegisterType((*PutObjectResponse)(nil), "proto.PutObjectResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "proto.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "proto.GetObjectResponse")
	proto.RegisterType((*GetObjectPresignedUrlRequest)(nil), "proto.GetObjectPresignedUrlRequest")
	proto.RegisterType((*GetObjectPresignedUrlResponse)(nil), "proto.GetObjectPresignedUrlResponse")
	proto.RegisterType((*PutObjectPresignedUrlRequest)(nil), "proto.PutObjectPresignedUrlRequest")
	proto.RegisterType((*PutObjectPresignedUrlResponse)(nil), "proto.PutObjectPresignedUrlResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xbd, 0x6e, 0xd4, 0x40,
	0x10, 0x96, 0xef, 0x27, 0xe1, 0x06, 0x09, 0x9c, 0x0d, 0x07, 0xcb, 0x71, 0x44, 0xa7, 0x85, 0x22,
	0x4a, 0x91, 0x93, 0xa0, 0xa3, 0xa3, 0xa2, 0x42, 0x44, 0x17, 0x51, 0x44, 0x54, 0x7b, 0xf6, 0x60,
	0x96, 0xf8, 0x76, 0x97, 0xf5, 0x1a, 0x12, 0x89, 0x02, 0xa5, 0xa0, 0xa0, 0xe5, 0xc9, 0x10, 0xaf,
	0xc0, 0x23, 0xf0, 0x00, 0x68, 0xd7, 0x8e, 0x71, 0xec, 0xcb, 0x35, 0xa7, 0x4b, 0xe5, 0xf1, 0xcc,
	0xf8, 0xf3, 0xf7, 0x7d, 0x33, 0xbb, 0x30, 0x30, 0x3a, 0x3a, 0xd4, 0x46, 0x59, 0x45, 0xfa, 0xfe,
	0x31, 0x1a, 0x27, 0x4a, 0x25, 0x29, 0x4e, 0xb9, 0x16, 0x53, 0x2e, 0xa5, 0xb2, 0xdc, 0x0a, 0x25,
	0xb3, 0xa2, 0x89, 0xfd, 0xe8, 0x40, 0x78, 0x94, 0xdb, 0x37, 0xf3, 0x8f, 0x18, 0xd9, 0x19, 0x7e,
	0xca, 0x31, 0xb3, 0xe4, 0x1e, 0xf4, 0x33, 0xab, 0x0c, 0xd2, 0x60, 0x12, 0xec, 0x0f, 0x66, 0xc5,
	0x0b, 0xd9, 0x03, 0x98, 0xe7, 0xd1, 0x29, 0x5a, 0xc9, 0x17, 0x48, 0x3b, 0xbe, 0x54, 0xcb, 0x90,
	0x10, 0xba, 0xa7, 0x78, 0x4e, 0xbb, 0xbe, 0xe0, 0x42, 0xf7, 0x85, 0xce, 0xe7, 0xa9, 0x88, 0x0c,
	0xf2, 0x98, 0xf6, 0x8a, 0x2f, 0xfe, 0x67, 0xc8, 0x04, 0x6e, 0x47, 0x4a, 0x5a, 0x94, 0xd6, 0x9e,
	0x6b, 0xa4, 0x7d, 0xdf, 0x50, 0x4f, 0x91, 0x03, 0x08, 0xcb, 0xd7, 0x05, 0x3f, 0x4b, 0x51, 0x26,
	0xf6, 0x03, 0xdd, 0x9a, 0x04, 0xfb, 0xdd, 0x59, 0x2b, 0xef, 0xd0, 0xde, 0x8b, 0x14, 0xcb, 0x3c,
	0xdd, 0x2e, 0xd0, 0x6a, 0x29, 0xc7, 0x07, 0xcf, 0xb4, 0x30, 0x68, 0xc5, 0x02, 0xe9, 0x2d, 0x8f,
	0x53, 0xcb, 0xb0, 0xd7, 0xb0, 0x53, 0xf3, 0x22, 0xd3, 0x4a, 0x66, 0x48, 0x08, 0xf4, 0x22, 0x15,
	0x17, 0x5e, 0xf4, 0x67, 0x3e, 0x76, 0x52, 0x17, 0x59, 0x52, 0x7a, 0xe0, 0x42, 0xd7, 0x15, 0x73,
	0xcb, 0x4b, 0xf5, 0x3e, 0x66, 0x5f, 0x21, 0x7c, 0x85, 0x1b, 0xb2, 0xb6, 0x61, 0x5d, 0xaf, 0x65,
	0x9d, 0x13, 0x53, 0xfb, 0xfb, 0xda, 0x62, 0xbe, 0x07, 0x30, 0xae, 0xf0, 0x8e, 0x0c, 0x66, 0x22,
	0x91, 0x18, 0xbf, 0x35, 0xe9, 0x06, 0x96, 0xa6, 0x36, 0xa4, 0x5e, 0x6b, 0x48, 0x27, 0xf0, 0xf8,
	0x1a, 0x1e, 0x6b, 0x6b, 0xfc, 0x1b, 0xc0, 0xb8, 0x5a, 0x80, 0x0d, 0x6b, 0xbc, 0xc1, 0x83, 0x71,
	0xd5, 0xd1, 0xed, 0x65, 0x8e, 0x5e, 0xa3, 0x7a, 0x5d, 0x47, 0x9f, 0xfd, 0xea, 0xc2, 0xdd, 0x63,
	0x67, 0xd2, 0x4b, 0x2d, 0x8e, 0xd1, 0x7c, 0x16, 0x11, 0x92, 0x13, 0x18, 0x54, 0xbf, 0x23, 0x0f,
	0x8a, 0x7b, 0xe8, 0xb0, 0x79, 0x07, 0x8d, 0x68, 0xbb, 0x50, 0xb0, 0x61, 0x0f, 0x2f, 0x7e, 0xff,
	0xf9, 0xd9, 0xd9, 0x65, 0x77, 0xa6, 0xca, 0x17, 0xa6, 0xb9, 0x4e, 0x15, 0x8f, 0x5f, 0x04, 0x07,
	0xe4, 0x1d, 0x0c, 0xaa, 0xdd, 0xa8, 0xa0, 0x9b, 0x67, 0xb0, 0x82, 0x6e, 0x1d, 0x0f, 0xf6, 0xc8,
	0x43, 0x0f, 0x59, 0x78, 0x09, 0x1d, 0xab, 0x2f, 0xf2, 0x12, 0xfc, 0x22, 0x80, 0xe1, 0xd2, 0xcd,
	0x23, 0x4f, 0x9a, 0x80, 0x4b, 0x76, 0x67, 0xf4, 0x74, 0x75, 0x53, 0xc9, 0x60, 0xcf, 0x33, 0xa0,
	0x6c, 0xb7, 0xc9, 0x20, 0x37, 0xa9, 0x23, 0xf1, 0x2d, 0x80, 0xe1, 0xd2, 0x61, 0x55, 0x24, 0x56,
	0x2d, 0x70, 0x45, 0x62, 0xe5, 0xbc, 0xd9, 0xd8, 0x93, 0xb8, 0xcf, 0x76, 0xae, 0x3a, 0x5c, 0x50,
	0x98, 0x6f, 0x79, 0x88, 0xe7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x52, 0xcb, 0x49, 0x9c, 0x6b,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreApiServiceClient is the client API for StoreApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreApiServiceClient interface {
	PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	GetObjectPresignedUrl(ctx context.Context, in *GetObjectPresignedUrlRequest, opts ...grpc.CallOption) (*GetObjectPresignedUrlResponse, error)
	PutObjectPresignedUrl(ctx context.Context, in *PutObjectPresignedUrlRequest, opts ...grpc.CallOption) (*PutObjectPresignedUrlResponse, error)
}

type storeApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreApiServiceClient(cc *grpc.ClientConn) StoreApiServiceClient {
	return &storeApiServiceClient{cc}
}

func (c *storeApiServiceClient) PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) GetObjectPresignedUrl(ctx context.Context, in *GetObjectPresignedUrlRequest, opts ...grpc.CallOption) (*GetObjectPresignedUrlResponse, error) {
	out := new(GetObjectPresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/GetObjectPresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) PutObjectPresignedUrl(ctx context.Context, in *PutObjectPresignedUrlRequest, opts ...grpc.CallOption) (*PutObjectPresignedUrlResponse, error) {
	out := new(PutObjectPresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/PutObjectPresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreApiServiceServer is the server API for StoreApiService service.
type StoreApiServiceServer interface {
	PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	GetObjectPresignedUrl(context.Context, *GetObjectPresignedUrlRequest) (*GetObjectPresignedUrlResponse, error)
	PutObjectPresignedUrl(context.Context, *PutObjectPresignedUrlRequest) (*PutObjectPresignedUrlResponse, error)
}

func RegisterStoreApiServiceServer(s *grpc.Server, srv StoreApiServiceServer) {
	s.RegisterService(&_StoreApiService_serviceDesc, srv)
}

func _StoreApiService_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).PutObject(ctx, req.(*PutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_GetObjectPresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).GetObjectPresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/GetObjectPresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).GetObjectPresignedUrl(ctx, req.(*GetObjectPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_PutObjectPresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).PutObjectPresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/PutObjectPresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).PutObjectPresignedUrl(ctx, req.(*PutObjectPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StoreApiService",
	HandlerType: (*StoreApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutObject",
			Handler:    _StoreApiService_PutObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _StoreApiService_GetObject_Handler,
		},
		{
			MethodName: "GetObjectPresignedUrl",
			Handler:    _StoreApiService_GetObjectPresignedUrl_Handler,
		},
		{
			MethodName: "PutObjectPresignedUrl",
			Handler:    _StoreApiService_PutObjectPresignedUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
