// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	_ "wps_store/proto/google/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutObjectRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectRequest) Reset()         { *m = PutObjectRequest{} }
func (m *PutObjectRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest) ProtoMessage()    {}
func (*PutObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *PutObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest.Unmarshal(m, b)
}
func (m *PutObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest.Marshal(b, m, deterministic)
}
func (m *PutObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest.Merge(m, src)
}
func (m *PutObjectRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest.Size(m)
}
func (m *PutObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest proto.InternalMessageInfo

func (m *PutObjectRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type PutObjectResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectResponse) Reset()         { *m = PutObjectResponse{} }
func (m *PutObjectResponse) String() string { return proto.CompactTextString(m) }
func (*PutObjectResponse) ProtoMessage()    {}
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *PutObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectResponse.Unmarshal(m, b)
}
func (m *PutObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectResponse.Marshal(b, m, deterministic)
}
func (m *PutObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectResponse.Merge(m, src)
}
func (m *PutObjectResponse) XXX_Size() int {
	return xxx_messageInfo_PutObjectResponse.Size(m)
}
func (m *PutObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectResponse proto.InternalMessageInfo

func (m *PutObjectResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutObjectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PutObjectResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetObjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetObjectResponse struct {
	Res                  string   `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

func init() {
	proto.RegisterType((*PutObjectRequest)(nil), "proto.PutObjectRequest")
	proto.RegisterType((*PutObjectResponse)(nil), "proto.PutObjectResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "proto.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "proto.GetObjectResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x4e, 0xf3, 0x40,
	0x10, 0x85, 0xe5, 0x38, 0x89, 0xe4, 0x29, 0xfe, 0xdf, 0x59, 0x04, 0x98, 0x40, 0x81, 0x56, 0x02,
	0xa1, 0x14, 0xb1, 0x04, 0x1d, 0x1d, 0x15, 0x15, 0x02, 0x39, 0x15, 0xa2, 0x5a, 0xdb, 0x23, 0xcb,
	0x90, 0xec, 0x2c, 0xde, 0x35, 0xf4, 0x5c, 0x81, 0x53, 0x51, 0x73, 0x05, 0x0e, 0x82, 0x3c, 0x36,
	0x56, 0xe4, 0x54, 0x7e, 0xde, 0xf9, 0xe6, 0xbd, 0x79, 0x10, 0x54, 0x26, 0x5b, 0x9a, 0x8a, 0x1c,
	0x89, 0x09, 0x7f, 0xe6, 0x27, 0x05, 0x51, 0xb1, 0xc6, 0x58, 0x99, 0x32, 0x56, 0x5a, 0x93, 0x53,
	0xae, 0x24, 0x6d, 0x5b, 0x48, 0x2e, 0x20, 0x7c, 0xa8, 0xdd, 0x7d, 0xfa, 0x8c, 0x99, 0x4b, 0xf0,
	0xb5, 0x46, 0xeb, 0xc4, 0x01, 0x4c, 0xd3, 0x3a, 0x7b, 0x41, 0x17, 0x79, 0xa7, 0xde, 0x45, 0x90,
	0x74, 0x7f, 0xf2, 0x0e, 0x66, 0x5b, 0xac, 0x35, 0xa4, 0x2d, 0x0a, 0x01, 0xe3, 0x8c, 0x72, 0x64,
	0x74, 0x92, 0xb0, 0x16, 0x21, 0xf8, 0x1b, 0x5b, 0x44, 0x23, 0xde, 0x6e, 0x64, 0x43, 0xe5, 0xca,
	0xa9, 0xc8, 0xe7, 0x27, 0xd6, 0xf2, 0x1c, 0xc2, 0x5b, 0x1c, 0x44, 0x0b, 0x18, 0x6b, 0xb5, 0xc1,
	0x2e, 0x98, 0xb5, 0x3c, 0x83, 0xd9, 0x16, 0xd7, 0xc5, 0x86, 0xe0, 0x57, 0x68, 0x3b, 0xae, 0x91,
	0x97, 0x5f, 0x1e, 0xfc, 0x5f, 0x39, 0xaa, 0xf0, 0xc6, 0x94, 0x2b, 0xac, 0xde, 0xca, 0x0c, 0xc5,
	0x23, 0x04, 0xfd, 0xc5, 0xe2, 0xb0, 0xad, 0xbc, 0x1c, 0xf6, 0x9d, 0x47, 0xbb, 0x83, 0x36, 0x45,
	0x1e, 0x7d, 0x7c, 0xff, 0x7c, 0x8e, 0xf6, 0xe4, 0xbf, 0x98, 0x78, 0x10, 0xd7, 0x66, 0x4d, 0x2a,
	0xbf, 0xf6, 0x16, 0xe2, 0x09, 0x82, 0xfe, 0xaa, 0xde, 0x7a, 0xd8, 0xa7, 0xb7, 0xde, 0x29, 0x20,
	0x8f, 0xd9, 0x7a, 0x5f, 0x86, 0x7f, 0xd6, 0x39, 0xbd, 0xeb, 0xce, 0x3c, 0x9d, 0xf2, 0xd6, 0xd5,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xd3, 0xf0, 0xca, 0xce, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreApiServiceClient is the client API for StoreApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreApiServiceClient interface {
	PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
}

type storeApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreApiServiceClient(cc *grpc.ClientConn) StoreApiServiceClient {
	return &storeApiServiceClient{cc}
}

func (c *storeApiServiceClient) PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreApiServiceServer is the server API for StoreApiService service.
type StoreApiServiceServer interface {
	PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
}

func RegisterStoreApiServiceServer(s *grpc.Server, srv StoreApiServiceServer) {
	s.RegisterService(&_StoreApiService_serviceDesc, srv)
}

func _StoreApiService_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).PutObject(ctx, req.(*PutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StoreApiService",
	HandlerType: (*StoreApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutObject",
			Handler:    _StoreApiService_PutObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _StoreApiService_GetObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
