// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
	_ "s3-micro/proto/google/api"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateBucketRequest struct {
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Publicread           string   `protobuf:"bytes,4,opt,name=publicread,proto3" json:"publicread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketRequest) Reset()         { *m = CreateBucketRequest{} }
func (m *CreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBucketRequest) ProtoMessage()    {}
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{0}
}

func (m *CreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketRequest.Unmarshal(m, b)
}
func (m *CreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *CreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketRequest.Merge(m, src)
}
func (m *CreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBucketRequest.Size(m)
}
func (m *CreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketRequest proto.InternalMessageInfo

func (m *CreateBucketRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *CreateBucketRequest) GetPublicread() string {
	if m != nil {
		return m.Publicread
	}
	return ""
}

type CreateBucketResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketResponse) Reset()         { *m = CreateBucketResponse{} }
func (m *CreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBucketResponse) ProtoMessage()    {}
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{1}
}

func (m *CreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketResponse.Unmarshal(m, b)
}
func (m *CreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *CreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketResponse.Merge(m, src)
}
func (m *CreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBucketResponse.Size(m)
}
func (m *CreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketResponse proto.InternalMessageInfo

func (m *CreateBucketResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateBucketResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateBucketResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DeleteBucketRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketRequest) Reset()         { *m = DeleteBucketRequest{} }
func (m *DeleteBucketRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketRequest) ProtoMessage()    {}
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{2}
}

func (m *DeleteBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketRequest.Unmarshal(m, b)
}
func (m *DeleteBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketRequest.Merge(m, src)
}
func (m *DeleteBucketRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketRequest.Size(m)
}
func (m *DeleteBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketRequest proto.InternalMessageInfo

func (m *DeleteBucketRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *DeleteBucketRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

type DeleteBucketResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketResponse) Reset()         { *m = DeleteBucketResponse{} }
func (m *DeleteBucketResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketResponse) ProtoMessage()    {}
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{3}
}

func (m *DeleteBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketResponse.Unmarshal(m, b)
}
func (m *DeleteBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketResponse.Merge(m, src)
}
func (m *DeleteBucketResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketResponse.Size(m)
}
func (m *DeleteBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketResponse proto.InternalMessageInfo

func (m *DeleteBucketResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteBucketResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DeleteBucketResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ListBucketRequest struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBucketRequest) Reset()         { *m = ListBucketRequest{} }
func (m *ListBucketRequest) String() string { return proto.CompactTextString(m) }
func (*ListBucketRequest) ProtoMessage()    {}
func (*ListBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{4}
}

func (m *ListBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketRequest.Unmarshal(m, b)
}
func (m *ListBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketRequest.Marshal(b, m, deterministic)
}
func (m *ListBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketRequest.Merge(m, src)
}
func (m *ListBucketRequest) XXX_Size() int {
	return xxx_messageInfo_ListBucketRequest.Size(m)
}
func (m *ListBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketRequest proto.InternalMessageInfo

func (m *ListBucketRequest) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type ListBucketResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ListBucket `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListBucketResponse) Reset()         { *m = ListBucketResponse{} }
func (m *ListBucketResponse) String() string { return proto.CompactTextString(m) }
func (*ListBucketResponse) ProtoMessage()    {}
func (*ListBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{5}
}

func (m *ListBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketResponse.Unmarshal(m, b)
}
func (m *ListBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketResponse.Marshal(b, m, deterministic)
}
func (m *ListBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketResponse.Merge(m, src)
}
func (m *ListBucketResponse) XXX_Size() int {
	return xxx_messageInfo_ListBucketResponse.Size(m)
}
func (m *ListBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketResponse proto.InternalMessageInfo

func (m *ListBucketResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListBucketResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListBucketResponse) GetData() *ListBucket {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListBucket struct {
	Bucket               []string `protobuf:"bytes,1,rep,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBucket) Reset()         { *m = ListBucket{} }
func (m *ListBucket) String() string { return proto.CompactTextString(m) }
func (*ListBucket) ProtoMessage()    {}
func (*ListBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{6}
}

func (m *ListBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucket.Unmarshal(m, b)
}
func (m *ListBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucket.Marshal(b, m, deterministic)
}
func (m *ListBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucket.Merge(m, src)
}
func (m *ListBucket) XXX_Size() int {
	return xxx_messageInfo_ListBucket.Size(m)
}
func (m *ListBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucket.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucket proto.InternalMessageInfo

func (m *ListBucket) GetBucket() []string {
	if m != nil {
		return m.Bucket
	}
	return nil
}

type PutObjectRequest struct {
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Publicread           string   `protobuf:"bytes,4,opt,name=publicread,proto3" json:"publicread,omitempty"`
	Contenttype          string   `protobuf:"bytes,5,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	Contentmaxlength     int64    `protobuf:"varint,6,opt,name=contentmaxlength,proto3" json:"contentmaxlength,omitempty"`
	Filecontent          string   `protobuf:"bytes,7,opt,name=filecontent,proto3" json:"filecontent,omitempty"`
	Expiretime           int64    `protobuf:"varint,8,opt,name=expiretime,proto3" json:"expiretime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectRequest) Reset()         { *m = PutObjectRequest{} }
func (m *PutObjectRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectRequest) ProtoMessage()    {}
func (*PutObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{7}
}

func (m *PutObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectRequest.Unmarshal(m, b)
}
func (m *PutObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectRequest.Marshal(b, m, deterministic)
}
func (m *PutObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectRequest.Merge(m, src)
}
func (m *PutObjectRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectRequest.Size(m)
}
func (m *PutObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectRequest proto.InternalMessageInfo

func (m *PutObjectRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *PutObjectRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutObjectRequest) GetPublicread() string {
	if m != nil {
		return m.Publicread
	}
	return ""
}

func (m *PutObjectRequest) GetContenttype() string {
	if m != nil {
		return m.Contenttype
	}
	return ""
}

func (m *PutObjectRequest) GetContentmaxlength() int64 {
	if m != nil {
		return m.Contentmaxlength
	}
	return 0
}

func (m *PutObjectRequest) GetFilecontent() string {
	if m != nil {
		return m.Filecontent
	}
	return ""
}

func (m *PutObjectRequest) GetExpiretime() int64 {
	if m != nil {
		return m.Expiretime
	}
	return 0
}

type PutObjectResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectResponse) Reset()         { *m = PutObjectResponse{} }
func (m *PutObjectResponse) String() string { return proto.CompactTextString(m) }
func (*PutObjectResponse) ProtoMessage()    {}
func (*PutObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{8}
}

func (m *PutObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectResponse.Unmarshal(m, b)
}
func (m *PutObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectResponse.Marshal(b, m, deterministic)
}
func (m *PutObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectResponse.Merge(m, src)
}
func (m *PutObjectResponse) XXX_Size() int {
	return xxx_messageInfo_PutObjectResponse.Size(m)
}
func (m *PutObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectResponse proto.InternalMessageInfo

func (m *PutObjectResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutObjectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PutObjectResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetObjectRequest struct {
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Contenttype          string   `protobuf:"bytes,4,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{9}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *GetObjectRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetObjectRequest) GetContenttype() string {
	if m != nil {
		return m.Contenttype
	}
	return ""
}

type GetObjectResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{10}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetObjectResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetObjectResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetObjectPresignedUrlRequest struct {
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Expiretime           int64    `protobuf:"varint,4,opt,name=expiretime,proto3" json:"expiretime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectPresignedUrlRequest) Reset()         { *m = GetObjectPresignedUrlRequest{} }
func (m *GetObjectPresignedUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectPresignedUrlRequest) ProtoMessage()    {}
func (*GetObjectPresignedUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{11}
}

func (m *GetObjectPresignedUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectPresignedUrlRequest.Unmarshal(m, b)
}
func (m *GetObjectPresignedUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectPresignedUrlRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectPresignedUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectPresignedUrlRequest.Merge(m, src)
}
func (m *GetObjectPresignedUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectPresignedUrlRequest.Size(m)
}
func (m *GetObjectPresignedUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectPresignedUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectPresignedUrlRequest proto.InternalMessageInfo

func (m *GetObjectPresignedUrlRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *GetObjectPresignedUrlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetObjectPresignedUrlRequest) GetExpiretime() int64 {
	if m != nil {
		return m.Expiretime
	}
	return 0
}

type GetObjectPresignedUrlResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectPresignedUrlResponse) Reset()         { *m = GetObjectPresignedUrlResponse{} }
func (m *GetObjectPresignedUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectPresignedUrlResponse) ProtoMessage()    {}
func (*GetObjectPresignedUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{12}
}

func (m *GetObjectPresignedUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectPresignedUrlResponse.Unmarshal(m, b)
}
func (m *GetObjectPresignedUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectPresignedUrlResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectPresignedUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectPresignedUrlResponse.Merge(m, src)
}
func (m *GetObjectPresignedUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectPresignedUrlResponse.Size(m)
}
func (m *GetObjectPresignedUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectPresignedUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectPresignedUrlResponse proto.InternalMessageInfo

func (m *GetObjectPresignedUrlResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetObjectPresignedUrlResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetObjectPresignedUrlResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PutObjectPresignedUrlRequest struct {
	Bucketname           string   `protobuf:"bytes,2,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Publicread           string   `protobuf:"bytes,4,opt,name=publicread,proto3" json:"publicread,omitempty"`
	Contenttype          string   `protobuf:"bytes,5,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	Contentmaxlength     int64    `protobuf:"varint,6,opt,name=contentmaxlength,proto3" json:"contentmaxlength,omitempty"`
	Expiretime           int64    `protobuf:"varint,7,opt,name=expiretime,proto3" json:"expiretime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectPresignedUrlRequest) Reset()         { *m = PutObjectPresignedUrlRequest{} }
func (m *PutObjectPresignedUrlRequest) String() string { return proto.CompactTextString(m) }
func (*PutObjectPresignedUrlRequest) ProtoMessage()    {}
func (*PutObjectPresignedUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{13}
}

func (m *PutObjectPresignedUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectPresignedUrlRequest.Unmarshal(m, b)
}
func (m *PutObjectPresignedUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectPresignedUrlRequest.Marshal(b, m, deterministic)
}
func (m *PutObjectPresignedUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectPresignedUrlRequest.Merge(m, src)
}
func (m *PutObjectPresignedUrlRequest) XXX_Size() int {
	return xxx_messageInfo_PutObjectPresignedUrlRequest.Size(m)
}
func (m *PutObjectPresignedUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectPresignedUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectPresignedUrlRequest proto.InternalMessageInfo

func (m *PutObjectPresignedUrlRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetPublicread() string {
	if m != nil {
		return m.Publicread
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetContenttype() string {
	if m != nil {
		return m.Contenttype
	}
	return ""
}

func (m *PutObjectPresignedUrlRequest) GetContentmaxlength() int64 {
	if m != nil {
		return m.Contentmaxlength
	}
	return 0
}

func (m *PutObjectPresignedUrlRequest) GetExpiretime() int64 {
	if m != nil {
		return m.Expiretime
	}
	return 0
}

type PutObjectPresignedUrlResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutObjectPresignedUrlResponse) Reset()         { *m = PutObjectPresignedUrlResponse{} }
func (m *PutObjectPresignedUrlResponse) String() string { return proto.CompactTextString(m) }
func (*PutObjectPresignedUrlResponse) ProtoMessage()    {}
func (*PutObjectPresignedUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{14}
}

func (m *PutObjectPresignedUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutObjectPresignedUrlResponse.Unmarshal(m, b)
}
func (m *PutObjectPresignedUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutObjectPresignedUrlResponse.Marshal(b, m, deterministic)
}
func (m *PutObjectPresignedUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutObjectPresignedUrlResponse.Merge(m, src)
}
func (m *PutObjectPresignedUrlResponse) XXX_Size() int {
	return xxx_messageInfo_PutObjectPresignedUrlResponse.Size(m)
}
func (m *PutObjectPresignedUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutObjectPresignedUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutObjectPresignedUrlResponse proto.InternalMessageInfo

func (m *PutObjectPresignedUrlResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PutObjectPresignedUrlResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PutObjectPresignedUrlResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type UpdateConfigStoreInfoRequest struct {
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Accesskey            string   `protobuf:"bytes,3,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Secretkey            string   `protobuf:"bytes,4,opt,name=secretkey,proto3" json:"secretkey,omitempty"`
	Region               string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigStoreInfoRequest) Reset()         { *m = UpdateConfigStoreInfoRequest{} }
func (m *UpdateConfigStoreInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigStoreInfoRequest) ProtoMessage()    {}
func (*UpdateConfigStoreInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{15}
}

func (m *UpdateConfigStoreInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigStoreInfoRequest.Unmarshal(m, b)
}
func (m *UpdateConfigStoreInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigStoreInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConfigStoreInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigStoreInfoRequest.Merge(m, src)
}
func (m *UpdateConfigStoreInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigStoreInfoRequest.Size(m)
}
func (m *UpdateConfigStoreInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigStoreInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigStoreInfoRequest proto.InternalMessageInfo

func (m *UpdateConfigStoreInfoRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UpdateConfigStoreInfoRequest) GetAccesskey() string {
	if m != nil {
		return m.Accesskey
	}
	return ""
}

func (m *UpdateConfigStoreInfoRequest) GetSecretkey() string {
	if m != nil {
		return m.Secretkey
	}
	return ""
}

func (m *UpdateConfigStoreInfoRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type UpdateConfigStoreInfoResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigStoreInfoResponse) Reset()         { *m = UpdateConfigStoreInfoResponse{} }
func (m *UpdateConfigStoreInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigStoreInfoResponse) ProtoMessage()    {}
func (*UpdateConfigStoreInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{16}
}

func (m *UpdateConfigStoreInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigStoreInfoResponse.Unmarshal(m, b)
}
func (m *UpdateConfigStoreInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigStoreInfoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConfigStoreInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigStoreInfoResponse.Merge(m, src)
}
func (m *UpdateConfigStoreInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigStoreInfoResponse.Size(m)
}
func (m *UpdateConfigStoreInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigStoreInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigStoreInfoResponse proto.InternalMessageInfo

func (m *UpdateConfigStoreInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateConfigStoreInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UpdateConfigStoreInfoResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetConfigStoreInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigStoreInfoRequest) Reset()         { *m = GetConfigStoreInfoRequest{} }
func (m *GetConfigStoreInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigStoreInfoRequest) ProtoMessage()    {}
func (*GetConfigStoreInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{17}
}

func (m *GetConfigStoreInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigStoreInfoRequest.Unmarshal(m, b)
}
func (m *GetConfigStoreInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigStoreInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigStoreInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigStoreInfoRequest.Merge(m, src)
}
func (m *GetConfigStoreInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigStoreInfoRequest.Size(m)
}
func (m *GetConfigStoreInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigStoreInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigStoreInfoRequest proto.InternalMessageInfo

type GetConfigStoreInfoResponse struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *ConfigInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConfigStoreInfoResponse) Reset()         { *m = GetConfigStoreInfoResponse{} }
func (m *GetConfigStoreInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigStoreInfoResponse) ProtoMessage()    {}
func (*GetConfigStoreInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{18}
}

func (m *GetConfigStoreInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigStoreInfoResponse.Unmarshal(m, b)
}
func (m *GetConfigStoreInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigStoreInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigStoreInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigStoreInfoResponse.Merge(m, src)
}
func (m *GetConfigStoreInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigStoreInfoResponse.Size(m)
}
func (m *GetConfigStoreInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigStoreInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigStoreInfoResponse proto.InternalMessageInfo

func (m *GetConfigStoreInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetConfigStoreInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetConfigStoreInfoResponse) GetData() *ConfigInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type ConfigInfo struct {
	Accesskey            string   `protobuf:"bytes,1,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Secretkey            string   `protobuf:"bytes,2,opt,name=secretkey,proto3" json:"secretkey,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Endpoint             string   `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigInfo) Reset()         { *m = ConfigInfo{} }
func (m *ConfigInfo) String() string { return proto.CompactTextString(m) }
func (*ConfigInfo) ProtoMessage()    {}
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d74a5129edc93dca, []int{19}
}

func (m *ConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigInfo.Unmarshal(m, b)
}
func (m *ConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigInfo.Marshal(b, m, deterministic)
}
func (m *ConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigInfo.Merge(m, src)
}
func (m *ConfigInfo) XXX_Size() int {
	return xxx_messageInfo_ConfigInfo.Size(m)
}
func (m *ConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigInfo proto.InternalMessageInfo

func (m *ConfigInfo) GetAccesskey() string {
	if m != nil {
		return m.Accesskey
	}
	return ""
}

func (m *ConfigInfo) GetSecretkey() string {
	if m != nil {
		return m.Secretkey
	}
	return ""
}

func (m *ConfigInfo) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ConfigInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBucketRequest)(nil), "proto.CreateBucketRequest")
	proto.RegisterType((*CreateBucketResponse)(nil), "proto.CreateBucketResponse")
	proto.RegisterType((*DeleteBucketRequest)(nil), "proto.DeleteBucketRequest")
	proto.RegisterType((*DeleteBucketResponse)(nil), "proto.DeleteBucketResponse")
	proto.RegisterType((*ListBucketRequest)(nil), "proto.ListBucketRequest")
	proto.RegisterType((*ListBucketResponse)(nil), "proto.ListBucketResponse")
	proto.RegisterType((*ListBucket)(nil), "proto.ListBucket")
	proto.RegisterType((*PutObjectRequest)(nil), "proto.PutObjectRequest")
	proto.RegisterType((*PutObjectResponse)(nil), "proto.PutObjectResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "proto.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "proto.GetObjectResponse")
	proto.RegisterType((*GetObjectPresignedUrlRequest)(nil), "proto.GetObjectPresignedUrlRequest")
	proto.RegisterType((*GetObjectPresignedUrlResponse)(nil), "proto.GetObjectPresignedUrlResponse")
	proto.RegisterType((*PutObjectPresignedUrlRequest)(nil), "proto.PutObjectPresignedUrlRequest")
	proto.RegisterType((*PutObjectPresignedUrlResponse)(nil), "proto.PutObjectPresignedUrlResponse")
	proto.RegisterType((*UpdateConfigStoreInfoRequest)(nil), "proto.UpdateConfigStoreInfoRequest")
	proto.RegisterType((*UpdateConfigStoreInfoResponse)(nil), "proto.UpdateConfigStoreInfoResponse")
	proto.RegisterType((*GetConfigStoreInfoRequest)(nil), "proto.GetConfigStoreInfoRequest")
	proto.RegisterType((*GetConfigStoreInfoResponse)(nil), "proto.GetConfigStoreInfoResponse")
	proto.RegisterType((*ConfigInfo)(nil), "proto.ConfigInfo")
}

func init() { proto.RegisterFile("proto/rpc.proto", fileDescriptor_d74a5129edc93dca) }

var fileDescriptor_d74a5129edc93dca = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcf, 0x4f, 0xdb, 0x48,
	0x14, 0x96, 0xc9, 0x0f, 0xc8, 0x03, 0x2d, 0xc9, 0x84, 0x80, 0x09, 0x59, 0x94, 0xf5, 0xb2, 0x52,
	0x96, 0x03, 0x91, 0xd8, 0xdb, 0xde, 0x76, 0x59, 0x09, 0xad, 0xda, 0xaa, 0x28, 0x88, 0x03, 0xed,
	0xc9, 0xb1, 0x5f, 0xd2, 0x29, 0xce, 0x8c, 0x6b, 0x4f, 0x5a, 0x90, 0x5a, 0xa9, 0xe2, 0xd8, 0x6b,
	0xff, 0xb4, 0xde, 0x7b, 0xea, 0xa5, 0xf7, 0xfe, 0x01, 0xd5, 0x8c, 0x27, 0x8e, 0x13, 0x3b, 0x81,
	0xca, 0xa8, 0xa7, 0xce, 0xbc, 0xf7, 0xfa, 0x7d, 0xdf, 0xfb, 0xc6, 0x79, 0x0f, 0xd8, 0xf4, 0x03,
	0x2e, 0x78, 0x37, 0xf0, 0x9d, 0x23, 0x75, 0x22, 0x25, 0xf5, 0x4f, 0xb3, 0x35, 0xe4, 0x7c, 0xe8,
	0x61, 0xd7, 0xf6, 0x69, 0xd7, 0x66, 0x8c, 0x0b, 0x5b, 0x50, 0xce, 0xc2, 0xa8, 0xc8, 0xba, 0x80,
	0xfa, 0x49, 0x80, 0xb6, 0xc0, 0x7f, 0xc7, 0xce, 0x15, 0x8a, 0x1e, 0xbe, 0x1a, 0x63, 0x28, 0xc8,
	0x3e, 0x40, 0x5f, 0x05, 0x98, 0x3d, 0x42, 0x73, 0xa5, 0x6d, 0x74, 0x2a, 0xbd, 0x44, 0x44, 0xe6,
	0xfd, 0x71, 0xdf, 0xa3, 0x4e, 0x80, 0xb6, 0x6b, 0x16, 0xa3, 0xfc, 0x34, 0x62, 0x9d, 0xc1, 0xd6,
	0x2c, 0x6c, 0xe8, 0x73, 0x16, 0x22, 0x21, 0x50, 0x74, 0xb8, 0x8b, 0xa6, 0xd1, 0x36, 0x3a, 0xa5,
	0x9e, 0x3a, 0x93, 0x2a, 0x14, 0x46, 0xe1, 0x50, 0x93, 0xc8, 0xa3, 0xac, 0x72, 0x6d, 0x61, 0x9b,
	0x05, 0x15, 0x52, 0x67, 0xeb, 0x11, 0xd4, 0xff, 0x43, 0x0f, 0xe7, 0x85, 0x6e, 0x41, 0x29, 0x14,
	0x3c, 0x88, 0x10, 0x2b, 0xbd, 0xe8, 0x72, 0x97, 0x7c, 0x29, 0x6f, 0x16, 0x2c, 0xb7, 0xbc, 0x3f,
	0xa1, 0xf6, 0x98, 0x86, 0xe2, 0x1e, 0xe2, 0x2c, 0x1b, 0x48, 0xb2, 0xf4, 0x87, 0xa8, 0xff, 0x48,
	0x50, 0xaf, 0x1f, 0xd7, 0xa2, 0x47, 0x3c, 0x4a, 0xc0, 0x45, 0x6a, 0x0e, 0x00, 0xa6, 0x31, 0xb2,
	0x0d, 0xe5, 0xa8, 0x77, 0xd3, 0x68, 0x17, 0x3a, 0x95, 0x9e, 0xbe, 0x59, 0xdf, 0x0c, 0xa8, 0x9e,
	0x8d, 0xc5, 0xd3, 0xfe, 0x4b, 0x74, 0xee, 0xfd, 0xf2, 0x55, 0x28, 0x5c, 0xe1, 0x8d, 0xee, 0x5d,
	0x1e, 0xef, 0xfa, 0x16, 0x48, 0x1b, 0xd6, 0x1d, 0xce, 0x04, 0x32, 0x21, 0x6e, 0x7c, 0x34, 0x4b,
	0xaa, 0x20, 0x19, 0x22, 0x87, 0x50, 0xd5, 0xd7, 0x91, 0x7d, 0xed, 0x21, 0x1b, 0x8a, 0x17, 0x66,
	0xb9, 0x6d, 0x74, 0x0a, 0xbd, 0x54, 0x5c, 0xa2, 0x0d, 0xa8, 0x87, 0x3a, 0x6e, 0xae, 0x46, 0x68,
	0x89, 0x90, 0xd4, 0x83, 0xd7, 0x3e, 0x0d, 0x50, 0xd0, 0x11, 0x9a, 0x6b, 0x0a, 0x27, 0x11, 0xb1,
	0x9e, 0x40, 0x2d, 0xd1, 0x75, 0xee, 0x97, 0x1f, 0x40, 0xf5, 0x14, 0x73, 0x9b, 0x38, 0x67, 0x52,
	0x31, 0x65, 0x92, 0x94, 0x9d, 0xe0, 0xc9, 0x2d, 0xdb, 0x87, 0x56, 0x0c, 0x77, 0x16, 0x60, 0x48,
	0x87, 0x0c, 0xdd, 0x8b, 0xc0, 0xcb, 0xf5, 0x1d, 0x24, 0x7c, 0x2f, 0xa6, 0x7c, 0xbf, 0x84, 0x5f,
	0x17, 0x30, 0xe6, 0x6e, 0xe6, 0xb3, 0x01, 0xad, 0xf8, 0x4d, 0x1f, 0xac, 0x9b, 0x9f, 0xf8, 0x55,
	0xcf, 0x7a, 0xb7, 0x9a, 0xe5, 0xdd, 0x82, 0xfe, 0x72, 0x7b, 0xf7, 0xc1, 0x80, 0xd6, 0x85, 0xef,
	0xda, 0x02, 0x4f, 0x38, 0x1b, 0xd0, 0xe1, 0xb9, 0x1c, 0x52, 0xff, 0xb3, 0x01, 0x9f, 0x78, 0xb7,
	0x0d, 0x65, 0x97, 0x8f, 0x6c, 0xca, 0x34, 0x92, 0xbe, 0x91, 0x16, 0x54, 0x6c, 0xc7, 0xc1, 0x30,
	0x9c, 0x3a, 0x37, 0x0d, 0xc8, 0x6c, 0x88, 0x4e, 0x80, 0x42, 0x66, 0x23, 0xfb, 0xa6, 0x01, 0x89,
	0x19, 0xe0, 0x90, 0x72, 0xa6, 0x8d, 0xd3, 0x37, 0xd9, 0xe7, 0x02, 0x2d, 0xb9, 0xfb, 0xdc, 0x83,
	0xdd, 0x53, 0x14, 0xd9, 0x3d, 0x5a, 0x14, 0x9a, 0x59, 0xc9, 0x07, 0x98, 0xcd, 0x11, 0xa6, 0x82,
	0x8b, 0x74, 0xbc, 0x05, 0x98, 0xc6, 0x66, 0x4d, 0x34, 0x96, 0x9a, 0xb8, 0xb2, 0xd8, 0xc4, 0x42,
	0xd2, 0x44, 0xd2, 0x84, 0x35, 0x64, 0xae, 0xcf, 0x29, 0x13, 0xda, 0xf9, 0xf8, 0x7e, 0xfc, 0x75,
	0x15, 0x36, 0x55, 0x83, 0xff, 0xf8, 0xf4, 0x1c, 0x83, 0xd7, 0xd4, 0x41, 0xd2, 0x87, 0x8d, 0xe4,
	0xb2, 0x26, 0xcd, 0x89, 0xf4, 0xf4, 0x1f, 0x06, 0xcd, 0xbd, 0xcc, 0x5c, 0xe4, 0x93, 0xb5, 0x7b,
	0xfb, 0xe9, 0xcb, 0xc7, 0x95, 0xba, 0xf5, 0x4b, 0x37, 0xfa, 0x69, 0x75, 0x1d, 0x55, 0xf5, 0xb7,
	0x71, 0x28, 0x39, 0x92, 0x1b, 0x37, 0xe6, 0xc8, 0xd8, 0xe9, 0x31, 0x47, 0xd6, 0x8a, 0x4e, 0x73,
	0xb8, 0xaa, 0x4a, 0x72, 0x3c, 0x9b, 0xd9, 0x7a, 0x66, 0x7a, 0x39, 0x6a, 0xfc, 0xdd, 0x8c, 0x8c,
	0x46, 0xdf, 0x51, 0xe8, 0x35, 0x6b, 0x63, 0x82, 0xee, 0xd1, 0x50, 0x48, 0xec, 0x4b, 0xa8, 0xc4,
	0x3f, 0x40, 0xb2, 0xa3, 0x01, 0xe6, 0x97, 0x67, 0xd3, 0x4c, 0x27, 0x52, 0xb2, 0xb9, 0x4a, 0x74,
	0xc7, 0xbe, 0xc7, 0x6d, 0x57, 0x42, 0x3f, 0x87, 0x4a, 0x3c, 0x17, 0x63, 0xe8, 0xf9, 0x95, 0x12,
	0x43, 0xa7, 0x76, 0x80, 0xb5, 0xa7, 0xa0, 0x1b, 0x56, 0x75, 0x02, 0xed, 0xf2, 0x37, 0x6c, 0x02,
	0x7e, 0x6b, 0x40, 0x23, 0x73, 0xea, 0x92, 0xdf, 0xe7, 0x01, 0x33, 0xe6, 0x66, 0xf3, 0x60, 0x79,
	0x91, 0x56, 0xb0, 0xaf, 0x14, 0x98, 0x56, 0x7d, 0x5e, 0xc1, 0x38, 0xf0, 0xa4, 0x88, 0xf7, 0x06,
	0x34, 0x32, 0xc7, 0x57, 0x2c, 0x62, 0xd9, 0xf0, 0x8e, 0x45, 0x2c, 0x9d, 0x80, 0x56, 0x4b, 0x89,
	0xd8, 0xb6, 0x6a, 0xb3, 0x0e, 0x6b, 0x09, 0xef, 0xa0, 0x91, 0x39, 0x58, 0x62, 0x05, 0xcb, 0x46,
	0x60, 0xac, 0x60, 0xe9, 0x6c, 0x4a, 0xbc, 0xb1, 0xa3, 0x2a, 0x12, 0x6f, 0x1c, 0x02, 0x49, 0xcf,
	0x17, 0xd2, 0x9e, 0xba, 0xbb, 0x80, 0xf8, 0xb7, 0x25, 0x15, 0x9a, 0xd5, 0x54, 0xac, 0x84, 0x54,
	0x27, 0xac, 0x13, 0xf3, 0xfb, 0x65, 0xf5, 0x7f, 0xff, 0xfa, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x45,
	0x59, 0x53, 0xfc, 0x1a, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreApiServiceClient is the client API for StoreApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreApiServiceClient interface {
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error)
	ListBucket(ctx context.Context, in *ListBucketRequest, opts ...grpc.CallOption) (*ListBucketResponse, error)
	PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	GetObjectPresignedUrl(ctx context.Context, in *GetObjectPresignedUrlRequest, opts ...grpc.CallOption) (*GetObjectPresignedUrlResponse, error)
	PutObjectPresignedUrl(ctx context.Context, in *PutObjectPresignedUrlRequest, opts ...grpc.CallOption) (*PutObjectPresignedUrlResponse, error)
	UpdateConfigStoreInfo(ctx context.Context, in *UpdateConfigStoreInfoRequest, opts ...grpc.CallOption) (*UpdateConfigStoreInfoResponse, error)
	GetConfigStoreInfo(ctx context.Context, in *GetConfigStoreInfoRequest, opts ...grpc.CallOption) (*GetConfigStoreInfoResponse, error)
}

type storeApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreApiServiceClient(cc *grpc.ClientConn) StoreApiServiceClient {
	return &storeApiServiceClient{cc}
}

func (c *storeApiServiceClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/CreateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error) {
	out := new(DeleteBucketResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/DeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) ListBucket(ctx context.Context, in *ListBucketRequest, opts ...grpc.CallOption) (*ListBucketResponse, error) {
	out := new(ListBucketResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/ListBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) PutObject(ctx context.Context, in *PutObjectRequest, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) GetObjectPresignedUrl(ctx context.Context, in *GetObjectPresignedUrlRequest, opts ...grpc.CallOption) (*GetObjectPresignedUrlResponse, error) {
	out := new(GetObjectPresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/GetObjectPresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) PutObjectPresignedUrl(ctx context.Context, in *PutObjectPresignedUrlRequest, opts ...grpc.CallOption) (*PutObjectPresignedUrlResponse, error) {
	out := new(PutObjectPresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/PutObjectPresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) UpdateConfigStoreInfo(ctx context.Context, in *UpdateConfigStoreInfoRequest, opts ...grpc.CallOption) (*UpdateConfigStoreInfoResponse, error) {
	out := new(UpdateConfigStoreInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/UpdateConfigStoreInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeApiServiceClient) GetConfigStoreInfo(ctx context.Context, in *GetConfigStoreInfoRequest, opts ...grpc.CallOption) (*GetConfigStoreInfoResponse, error) {
	out := new(GetConfigStoreInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.StoreApiService/GetConfigStoreInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreApiServiceServer is the server API for StoreApiService service.
type StoreApiServiceServer interface {
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error)
	ListBucket(context.Context, *ListBucketRequest) (*ListBucketResponse, error)
	PutObject(context.Context, *PutObjectRequest) (*PutObjectResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	GetObjectPresignedUrl(context.Context, *GetObjectPresignedUrlRequest) (*GetObjectPresignedUrlResponse, error)
	PutObjectPresignedUrl(context.Context, *PutObjectPresignedUrlRequest) (*PutObjectPresignedUrlResponse, error)
	UpdateConfigStoreInfo(context.Context, *UpdateConfigStoreInfoRequest) (*UpdateConfigStoreInfoResponse, error)
	GetConfigStoreInfo(context.Context, *GetConfigStoreInfoRequest) (*GetConfigStoreInfoResponse, error)
}

func RegisterStoreApiServiceServer(s *grpc.Server, srv StoreApiServiceServer) {
	s.RegisterService(&_StoreApiService_serviceDesc, srv)
}

func _StoreApiService_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/CreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_ListBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).ListBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/ListBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).ListBucket(ctx, req.(*ListBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).PutObject(ctx, req.(*PutObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_GetObjectPresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).GetObjectPresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/GetObjectPresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).GetObjectPresignedUrl(ctx, req.(*GetObjectPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_PutObjectPresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjectPresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).PutObjectPresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/PutObjectPresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).PutObjectPresignedUrl(ctx, req.(*PutObjectPresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_UpdateConfigStoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigStoreInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).UpdateConfigStoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/UpdateConfigStoreInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).UpdateConfigStoreInfo(ctx, req.(*UpdateConfigStoreInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreApiService_GetConfigStoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigStoreInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreApiServiceServer).GetConfigStoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StoreApiService/GetConfigStoreInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreApiServiceServer).GetConfigStoreInfo(ctx, req.(*GetConfigStoreInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StoreApiService",
	HandlerType: (*StoreApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _StoreApiService_CreateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _StoreApiService_DeleteBucket_Handler,
		},
		{
			MethodName: "ListBucket",
			Handler:    _StoreApiService_ListBucket_Handler,
		},
		{
			MethodName: "PutObject",
			Handler:    _StoreApiService_PutObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _StoreApiService_GetObject_Handler,
		},
		{
			MethodName: "GetObjectPresignedUrl",
			Handler:    _StoreApiService_GetObjectPresignedUrl_Handler,
		},
		{
			MethodName: "PutObjectPresignedUrl",
			Handler:    _StoreApiService_PutObjectPresignedUrl_Handler,
		},
		{
			MethodName: "UpdateConfigStoreInfo",
			Handler:    _StoreApiService_UpdateConfigStoreInfo_Handler,
		},
		{
			MethodName: "GetConfigStoreInfo",
			Handler:    _StoreApiService_GetConfigStoreInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc.proto",
}
