# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc_pb2 as rpc__pb2


class StoreApiServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateBucket = channel.unary_unary(
        '/proto.StoreApiService/CreateBucket',
        request_serializer=rpc__pb2.CreateBucketRequest.SerializeToString,
        response_deserializer=rpc__pb2.CreateBucketResponse.FromString,
        )
    self.DeleteBucket = channel.unary_unary(
        '/proto.StoreApiService/DeleteBucket',
        request_serializer=rpc__pb2.DeleteBucketRequest.SerializeToString,
        response_deserializer=rpc__pb2.DeleteBucketResponse.FromString,
        )
    self.ListBucket = channel.unary_unary(
        '/proto.StoreApiService/ListBucket',
        request_serializer=rpc__pb2.ListBucketRequest.SerializeToString,
        response_deserializer=rpc__pb2.ListBucketResponse.FromString,
        )
    self.PutObject = channel.unary_unary(
        '/proto.StoreApiService/PutObject',
        request_serializer=rpc__pb2.PutObjectRequest.SerializeToString,
        response_deserializer=rpc__pb2.PutObjectResponse.FromString,
        )
    self.GetObject = channel.unary_unary(
        '/proto.StoreApiService/GetObject',
        request_serializer=rpc__pb2.GetObjectRequest.SerializeToString,
        response_deserializer=rpc__pb2.GetObjectResponse.FromString,
        )
    self.DeleteObject = channel.unary_unary(
        '/proto.StoreApiService/DeleteObject',
        request_serializer=rpc__pb2.DeleteObjectRequest.SerializeToString,
        response_deserializer=rpc__pb2.DeleteObjectResponse.FromString,
        )
    self.ListObject = channel.unary_unary(
        '/proto.StoreApiService/ListObject',
        request_serializer=rpc__pb2.ListObjectRequest.SerializeToString,
        response_deserializer=rpc__pb2.ListObjectResponse.FromString,
        )
    self.GetObjectPresignedUrl = channel.unary_unary(
        '/proto.StoreApiService/GetObjectPresignedUrl',
        request_serializer=rpc__pb2.GetObjectPresignedUrlRequest.SerializeToString,
        response_deserializer=rpc__pb2.GetObjectPresignedUrlResponse.FromString,
        )
    self.PutObjectPresignedUrl = channel.unary_unary(
        '/proto.StoreApiService/PutObjectPresignedUrl',
        request_serializer=rpc__pb2.PutObjectPresignedUrlRequest.SerializeToString,
        response_deserializer=rpc__pb2.PutObjectPresignedUrlResponse.FromString,
        )
    self.UpdateConfigStoreInfo = channel.unary_unary(
        '/proto.StoreApiService/UpdateConfigStoreInfo',
        request_serializer=rpc__pb2.UpdateConfigStoreInfoRequest.SerializeToString,
        response_deserializer=rpc__pb2.UpdateConfigStoreInfoResponse.FromString,
        )
    self.GetConfigStoreInfo = channel.unary_unary(
        '/proto.StoreApiService/GetConfigStoreInfo',
        request_serializer=rpc__pb2.GetConfigStoreInfoRequest.SerializeToString,
        response_deserializer=rpc__pb2.GetConfigStoreInfoResponse.FromString,
        )


class StoreApiServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateBucket(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBucket(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListBucket(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutObject(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObject(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteObject(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListObject(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObjectPresignedUrl(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutObjectPresignedUrl(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateConfigStoreInfo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConfigStoreInfo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StoreApiServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateBucket': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBucket,
          request_deserializer=rpc__pb2.CreateBucketRequest.FromString,
          response_serializer=rpc__pb2.CreateBucketResponse.SerializeToString,
      ),
      'DeleteBucket': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBucket,
          request_deserializer=rpc__pb2.DeleteBucketRequest.FromString,
          response_serializer=rpc__pb2.DeleteBucketResponse.SerializeToString,
      ),
      'ListBucket': grpc.unary_unary_rpc_method_handler(
          servicer.ListBucket,
          request_deserializer=rpc__pb2.ListBucketRequest.FromString,
          response_serializer=rpc__pb2.ListBucketResponse.SerializeToString,
      ),
      'PutObject': grpc.unary_unary_rpc_method_handler(
          servicer.PutObject,
          request_deserializer=rpc__pb2.PutObjectRequest.FromString,
          response_serializer=rpc__pb2.PutObjectResponse.SerializeToString,
      ),
      'GetObject': grpc.unary_unary_rpc_method_handler(
          servicer.GetObject,
          request_deserializer=rpc__pb2.GetObjectRequest.FromString,
          response_serializer=rpc__pb2.GetObjectResponse.SerializeToString,
      ),
      'DeleteObject': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteObject,
          request_deserializer=rpc__pb2.DeleteObjectRequest.FromString,
          response_serializer=rpc__pb2.DeleteObjectResponse.SerializeToString,
      ),
      'ListObject': grpc.unary_unary_rpc_method_handler(
          servicer.ListObject,
          request_deserializer=rpc__pb2.ListObjectRequest.FromString,
          response_serializer=rpc__pb2.ListObjectResponse.SerializeToString,
      ),
      'GetObjectPresignedUrl': grpc.unary_unary_rpc_method_handler(
          servicer.GetObjectPresignedUrl,
          request_deserializer=rpc__pb2.GetObjectPresignedUrlRequest.FromString,
          response_serializer=rpc__pb2.GetObjectPresignedUrlResponse.SerializeToString,
      ),
      'PutObjectPresignedUrl': grpc.unary_unary_rpc_method_handler(
          servicer.PutObjectPresignedUrl,
          request_deserializer=rpc__pb2.PutObjectPresignedUrlRequest.FromString,
          response_serializer=rpc__pb2.PutObjectPresignedUrlResponse.SerializeToString,
      ),
      'UpdateConfigStoreInfo': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateConfigStoreInfo,
          request_deserializer=rpc__pb2.UpdateConfigStoreInfoRequest.FromString,
          response_serializer=rpc__pb2.UpdateConfigStoreInfoResponse.SerializeToString,
      ),
      'GetConfigStoreInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfigStoreInfo,
          request_deserializer=rpc__pb2.GetConfigStoreInfoRequest.FromString,
          response_serializer=rpc__pb2.GetConfigStoreInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.StoreApiService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
